backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "gallery"
    label: "Fotos do Portfólio"
    files:
      - name: "gallery"
        label: "Galeria (Trabalhos)"
        file: "data/gallery.json"
        fields:
          - { label: "Fotos", name: "photos", widget: "list", fields: [
              { label: "Imagem", name: "image", widget: "image" },
              { label: "Descrição (opcional)", name: "alt", widget: "string", required: false }
            ] }
